defaults:
- config

paths:
  results_dir: ${paths.root_dir}/results/pref
  sweep_dir: ${paths.root_dir}/results_sweep/pref


hydra:
  run:
    dir: ${paths.results_dir}/${now:%Y%m%d_%H%M%S}_nqu=${data.nq_update}_nepochs=${sgd.n_epochs}

  sweep:
    dir: ${paths.sweep_dir}/${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
