[tool.ruff]
line-length = 88

# extend-select
# I: adding isort rules since i will be using CLI ruff in addition to sorting imports

# unfixable
# F401: do not remove unused imports
# F841: local variable is assigned to but never used

# ignore
# F722: multidimensional array annotation (jaxtyping)
# F821: single-dimensional array annotation (jaxtyping)
# E731: do not assign a lambda function to a variable
# E402: module level import not at top of file
[tool.ruff.lint]
extend-select = ["I"] 
unfixable = ["F401", "F841"] 
ignore = ["F722", "F821", "E731", "E402"]