defaults:
  - submitit_slurm

# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 1440 # 24 hours
cpus_per_task: 10 # 10 env rollout workers
gpus_per_node: null
tasks_per_node: 1
gpus_per_task: null
mem_gb: null
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: null
qos: null
comment: null
constraint: null
exclude: null
gres: shard:12 # 50 shards per GPU
cpus_per_gpu: null
mem_per_cpu: null
account: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null
# srun_args: null